### ISSUE TITLE
Add success toast

### ISSUE THREAD

**Issue by Arenukvern** [xsoulspace/sheets_concat_excel_vba_macro#1]
After macro is completed, need to add well-looking success toast.
Step 1:
- [x] make simple toast - logic
* show it after macro completed
* show text - Sheets successfully merged!
- [x] design well-looking styled success toast
* background and form style
* button style - must be well look like native excel or similar

Button states: 
- on hover
- idle

Reference how to do that:
https://www.thespreadsheetguru.com/blog/build-modern-vba-userforms

Step 2:

- [x] Make danger toast
button: ~red
text: Something went wrong.. Please try again, or ask for help at GitHub.
- [x]  Add ErrorHanlder with danger toast. Danger toast must show error number and description.
- [x] Make info toast:
text: String and grey button

Step 3:
- [x] Study class (evening -> 11)
* How to initialize class
* How to write and call class method
* How to write and call class sub
* How to make parent class
* Study class private/public variables

Parent class = Vegetable
Private variable: _age
Method: age() return vegetable age 
Sub: grow(days) vegetable age + days

Successor class = Carrot, potato

- [ ] Write toast class
Methods / Subs:
1. show type: enum, text: string
2. hide

Types: Success / Danger/Info

How to make a class that can manage alerts?
1. So that the alert call code is in one place
2. Create two methods in the class, open and close the alert
3. One method to open is to contain the type of alert to open.
For example, info, danger, success and alert text. For types do enum
To select an alert inside the method, open either through If Else or Salect case "

Usage:
toast.show type, text
toast.hide

**Comment by mixev** [comment]
@Arenukvern 
у меня вопрос по завершению процесса, как закрыть окно оповещения по нажатию кнопки?

**Comment by Arenukvern** [comment]
@mixev нужно выгрузить form по клику

Если из form
unload me

Если из любого другого модуля
Unload "NameOfForm"
